name: Entrega contínua

on:
  workflow_call:

jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: programa

      - name: Copy artifact to EC2 via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "programa,templates,assets"
          target: "/home/${{ secrets.REMOTE_USER }}" # Assumindo que REMOTE_USER é 'ubuntu'

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.0.3 # Esta é a versão mais recente
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            chmod +x programa
            sudo systemctl restart goapp.service
