name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      HOST: localhost
      DBPORT: 5432
      USER: root
      PASSWORD: root
      DBNAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest', 'ubuntu-18.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}

    - name: Install Docker and Docker Compose
      run: |
        # Instala Docker + Compose via script oficial
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        docker --version
        docker compose version

    - name: Build DB
      run: docker compose build

    - name: Create DB
      run: docker compose up -d

    - name: Run Tests
      run: go test -v main_test.go 
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: programa
        path: main

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

  Deploy_EC2:
    needs: build
    uses: ./.github/workflows/EC2.yml
    secrets: inherit
